stocks:
  - fars
  - foolad
  - ranfor
  - toreil
  - khodro
  - zagros
features:
  - open_return
  - high_return
  - low_return
  - close_return
  - avg_price_return
  - RSI
start_date: '2018-01-01'
adjusted: true
days_to_news: 3