name: Run Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "Amirarsalan83"
          MYSQL_DATABASE: stock_market
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          sleep 20

      - name: Import compressed SQL dump
        run: |
          gunzip -c database/stock_market.sql.gz | mysql -h 127.0.0.1 -u root -p"Amirarsalan83" stock_market

      - name: Run pipeline
        env:
          DB_USER: root
          DB_PASS: "Amirarsalan83"
          DB_HOST: 127.0.0.1
          DB_NAME: stock_market
        run: |
          python pipeline.py
          
      - name: Upload output folder
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pipeline-outputs
          path: output/
